module.exports =
  version: "5.2.0"
  Client: require "./client"
  Mustache: require "mustache"
  Controller: require "./controller"
  widgets:
    CollapsiblePanel: require "./widgets/collapsiblepanel"
    Display: require "./widgets/display"
    Panel: require "./widgets/panel"
    QueryInput: require "./widgets/queryinput"
    RangeFacet: require "./widgets/facets/rangefacet"
    ScrollDisplay: require "./widgets/scrolldisplay"
    TermsFacet: require "./widgets/facets/termfacet"
    Widget: require "./widgets/widget"
  util:
    addHelpers: require "./util/helpers"
    bean: require "bean"
    dfdom: require "./util/dfdom"
    currency: require "./util/currency"
    extend: require "extend"
    http: require "./util/http"
    md5: require "md5"
    qs: require "qs"
    throttle: require "lodash.throttle"
    uniqueId: require "./util/uniqueid"
  session: require "./session"
  stats: require "./stats"
